---
- name: Verify - K3s
  hosts: k3s_server[0]
  gather_facts: no
  become: yes
  tasks:
    - name: Get Cluster info
      ansible.builtin.shell: "/usr/local/bin/kubectl get node"
      register: output_get_node
      until: output_get_node.stdout_lines | length == 6
      retries: 60

    - debug:
        var: output_get_node.stdout_lines

    - assert:
        that: output_get_node.stdout_lines | length == 6