---
dependency:
  name: galaxy
driver:
  name: delegated

platforms:
  - name: ubuntu2204-1
    template_name: ubuntu-22-04
    groups:
      - k3s_server

  - name: ubuntu2204-2
    template_name: ubuntu-22-04
    groups:
      - k3s_server

  - name: ubuntu2204-3
    template_name: ubuntu-22-04
    groups:
      - k3s_server

  - name: ubuntu2204-4
    template_name: ubuntu-22-04
    groups:
      - k3s_agent
provisioner:
  name: ansible
  playbooks:
    create: ../../../setup/molecule/default/create.yml
    prepare: ../default-undeploy/prepare.yml
    destroy: ../../../setup/molecule/default/destroy.yml
    converge: ../default-undeploy/converge.yml
    verify: ../default-undeploy/verify.yml

verifier:
  name: ansible
