---
- name: Converge - Gather facts
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Gather Facts
      ansible.builtin.setup:
        gather_subset:
          - min
          - network
      register: setup_result
      until: setup_result.failed != true
      retries: 10

- name: Converge - Uninstall k3s server
  hosts: k3s_server:k3s_agent
  gather_facts: no
  become: yes
  tasks:
    - name: Include K3s uninstall.yml
      include_role:
        name: setup
        tasks_from: uninstall.yml