---
dependency:
  name: galaxy
driver:
  name: delegated

platforms:
  - name: ubuntu2004-1
    template_name: ubuntu-20-04
    groups:
      - k3s_server

  - name: ubuntu2004-2
    template_name: ubuntu-20-04
    groups:
      - k3s_server

  - name: ubuntu2004-3
    template_name: ubuntu-20-04
    groups:
      - k3s_server

  - name: ubuntu2004-4
    template_name: ubuntu-20-04
    groups:
      - k3s_agent
provisioner:
  name: ansible
  playbooks:
    create: ../default/create.yml
    prepare: ../default-install/converge.yml
    destroy: ../default/destroy.yml
    converge: ../default-uninstall/converge.yml
    verify: ../default-uninstall/verify.yml

verifier:
  name: ansible
