---
- set_fact:
    scale_down_node_names: "{{ scale_down_node_names | default ([]) + [ hostvars[item].ansible_hostname ] }}"
  loop: "{{ groups['scale_down_host'] }}"

- name: Cordon node
  ansible.builtin.shell: "/usr/local/bin/kubectl cordon {{ item }}"
  loop: "{{ scale_down_node_names }}"
  register: output_cordon
  failed_when:
    - output_cordon.rc == 1
    - not 'not found' in output_cordon.stderr
  changed_when: output_cordon.rc == 0
  until: output_cordon.rc == 0 or 'not found' in output_cordon.stderr
  retries: 10

- name: Delete node
  ansible.builtin.shell: "/usr/local/bin/kubectl delete node {{ item }}"
  loop: "{{ scale_down_node_names }}"
  register: output_delete
  failed_when:
    - output_delete.rc == 1
    - not 'not found' in output_delete.stderr
  changed_when: output_delete.rc == 0
  until: output_delete.rc == 0 or 'not found' in output_delete.stderr
  retries: 10