---
- name: Check if uninstall script exists (server)
  ansible.builtin.stat:
    path: "{{ uninstall_script_server_dest }}"
  register: uninstall_script_server

- name: Check if uninstall script exists (agent)
  ansible.builtin.stat:
    path: "{{ uninstall_script_agent_dest }}"
  register: uninstall_script_agent

- name: Run uninstall script (agent)
  ansible.builtin.shell: "{{ uninstall_script_agent_dest }}"
  register: output_uninstall_agent
  when: uninstall_script_agent.stat.exists

- name: Run uninstall script (server)
  ansible.builtin.shell: "{{ uninstall_script_server_dest }}"
  register: output_uninstall_server
  when: uninstall_script_server.stat.exists